source 'https://rubygems.org'
gem 'jekyll', '<4'
gem 'jekyll-archives'
gem 'jekyll-sitemap'
gem 'jekyll-paginate-v2'
gem 'jekyll-admin', group: :jekyll_plugins
gem "webrick", "~> 1.8"
gem "kramdown-parser-gfm"